### ISSUE TITLE
어플이라도 공유해주세요.

### ISSUE THREAD

**Issue by nardem** [ManDongI/ScriptableKakaoBot#2]
되는분에게 apk파일 받아서 하는데 키면 바로 꺼집니다.
그래서 responce.js 수정했는데도 정작 해보면 안되네요.
폰은 롤리팝입니다.

**Comment by ManDongI** [comment]
바로 꺼지는 현상은  js를 잘못 작성했거나 읽기 권한이 획득되지 않았을때 벌어집니다. response.js를 kbot 디렉토리에 제대로 넣으셨나요? response.js 내용을 보내주세요
