### ISSUE TITLE
Does this app apply KitKat?

### ISSUE THREAD

**Issue by ZINGDING** [ManDongI/ScriptableKakaoBot#3]
My phone Android Version is Kitkat.
But this program didn't work!

**Comment by ZINGDING** [comment]
I change Minsdkversion!

**Comment by ZINGDING** [comment]
But that app is still not working! :(

**Comment by ManDongI** [comment]
Kitkat doesn't implement `getRemoteInputs : API 20`;

**Comment by ManDongI** [comment]
Or did you install Android Wear app?

**Comment by ZINGDING** [comment]
@ManDongI  I install Android Wear App.

**Comment by ZINGDING** [comment]
OTL....

I think this app dosen't apply KitKat.
Because  when I upgrade custom rom from my kitkat rom, This app is working! :|....
