### ISSUE TITLE
Need a compiled APK file

### ISSUE THREAD

**Issue by DELOS-phardev** [ManDongI/ScriptableKakaoBot#4]
아시다시피 전 한국인입니다.

제목이 영어인건 그냥 허세니까 이해 부탁드립니다.

모바일 환경에서의 컴파일 과정에서 어려움을 겪고 있는 중이라

APK파일 공유 부탁드려 봅니다.

**Comment by ZINGDING** [comment]
[app-debug.zip](https://github.com/ManDongI/ScriptableKakaoBot/files/463034/app-debug.zip)
here!

**Comment by ManDongI** [comment]
네. 윗분이 보내주셨네요
